version: '3'
services:
    testnodeexpress-service:
      build: .
      volumes:
        - .:/usr/app 
        - /usr/app/node_modules       
      environment:
        NODE_ENV: development  
      ports:
        - 9030:9030
        - 9229:9229
      command: npm run start      
   